### ISSUE TITLE
i got an error after i type node register.js

### ISSUE THREAD

**Issue by chans12** [jonathonor/expireBot#3]
]
}
PS C:\Users\PC\OneDrive\Masaüstü\TimerBot\trialbot> node register.js
Started refreshing application (/) commands.
(node:7604) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
DiscordAPIError[0]: 404: Not Found
    at handleErrors (file:///C:/Users/PC/OneDrive/Masa%C3%BCst%C3%BC/TimerBot/trialbot/node_modules/@discordjs/rest/dist/index.mjs:588:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.runRequest (file:///C:/Users/PC/OneDrive/Masa%C3%BCst%C3%BC/TimerBot/trialbot/node_modules/@discordjs/rest/dist/index.mjs:969:23)
    at async SequentialHandler.queueRequest (file:///C:/Users/PC/OneDrive/Masa%C3%BCst%C3%BC/TimerBot/trialbot/node_modules/@discordjs/rest/dist/index.mjs:810:14)
    at async REST.request (file:///C:/Users/PC/OneDrive/Masa%C3%BCst%C3%BC/TimerBot/trialbot/node_modules/@discordjs/rest/dist/index.mjs:1335:22)
    at async file:///C:/Users/PC/OneDrive/Masa%C3%BCst%C3%BC/TimerBot/trialbot/register.js:40:5 {
  requestBody: {
    files: undefined,
    json: [ [SlashCommandBuilder], [SlashCommandBuilder] ]
  },
  rawError: { message: '404: Not Found', code: 0 },
  code: 0,
  status: 404,
  method: 'PUT',
  url: 'https://discord.com/api/v9/applications/1095615764507148340 / 1095615764507148340/commands'
  }
PS C:\Users\PC\OneDrive\Masaüstü\TimerBot\trialbot> node trialbot-lowdb.js
(node:2828) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\PC\OneDrive\Masaüstü\TimerBot\trialbot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:250
        throw new DiscordjsError(unrecoverableErrorCodeMap[error.code]);
              ^

Error [DisallowedIntents]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (C:\Users\PC\OneDrive\Masaüstü\TimerBot\trialbot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:250:15)
    at async Client.login (C:\Users\PC\OneDrive\Masaüstü\TimerBot\trialbot\node_modules\discord.js\src\client\Client.js:226:7) {
  code: 'DisallowedIntents'
}

**Comment by chethanyadav456** [comment]
Firstly, the error "DiscordAPIError[0]: 404: Not Found" indicates that the Discord API was unable to find the route for the command you are trying to create. This could be due to a few reasons:

1. You might not have provided the correct application ID in your config file. Double-check that the ID is correct.

2. You might not have authorized your bot with the "applications.commands" scope. Make sure you have authorized the bot and added the scope to the OAuth2 URL.

3. You might not have invited the bot to the server you are trying to create the command in. Make sure you have invited the bot and have given it the appropriate permissions.

To fix this issue, you should double-check your application ID, make sure you have authorized the bot with the correct scope, and invite the bot to the server.

Secondly, the error "Error [DisallowedIntents]: Privileged intent provided is not enabled or whitelisted." indicates that you are using a privileged intent that is not enabled for your bot. Discord has certain "privileged intents" (such as the "GUILD_MEMBERS" intent) that require additional verification before they can be used.

To fix this issue, you should go to the Discord Developer Portal, navigate to your bot's settings, and enable the necessary privileged intents. You should also make sure that your bot has the necessary permissions on the server to use these intents.

I hope this helps you fix your issues!

If u stil get the error u can contact me on discord - `Raaz#2233`

**Comment by chans12** [comment]
thank you i fixed the issue.

**Comment by jonathonor** [comment]
@chethanyadav456 thanks for the help on this, I overlooked it. closing issue.
